image: gitpod/workspace-full:latest

tasks:
  - name: Starting Go Web App
    init: go mod init gitpod-demo
    command: go mod tidy && go run ./cmd/main.go
ports:
  - name: Webserver listening at...
    port: 8080
    onOpen: open-browser
