image: gitpod/workspace-full:latest

tasks:
  - name: Starting Go Web App
    init: go mod tidy
    command: go run ./...
ports:
  - name: Webserver listening at...
    port: 8080
    onOpen: open-browser
